package com.core.presentation.theme.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3C8770)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF36816B)
val onPrimaryContainerLight = Color(0xFFF5FFF9)
val secondaryLight = Color(0xFF49645A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC8E6D9)
val onSecondaryContainerLight = Color(0xFF4D685E)
val tertiaryLight = Color(0xFFf7d160)
val onTertiaryLight = Color(0xFF000000)
val tertiaryContainerLight = Color(0xFFFFE59B)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF6F6F6)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFF7FAF6)
val onSurfaceLight = Color(0xFF181C1B)
val surfaceVariantLight = Color(0xFFDAE5DF)
val onSurfaceVariantLight = Color(0xFF3F4944)
val outlineLight = Color(0xFF6F7974)
val outlineVariantLight = Color(0xFFBEC9C3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D312F)
val inverseOnSurfaceLight = Color(0xFFEEF1EE)
val inversePrimaryLight = Color(0xFF8AD5BB)
val surfaceDimLight = Color(0xFFD8DBD7)
val surfaceBrightLight = Color(0xFFF7FAF6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F4F1)
val surfaceContainerLight = Color(0xFFECEFEB)
val surfaceContainerHighLight = Color(0xFFE6E9E5)
val surfaceContainerHighestLight = Color(0xFFE0E3E0)

val primaryDark = Color(0xFF3C8770)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF549E86)
val onPrimaryContainerDark = Color(0xFF00100A)
val secondaryDark = Color(0xFFAFCDC0)
val onSecondaryDark = Color(0xFF1B352C)
val secondaryContainerDark = Color(0xFF314C42)
val onSecondaryContainerDark = Color(0xFF9EBCAF)
val tertiaryDark = Color(0xFFf7d160)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFFFFE59B)
val onTertiaryContainerDark = Color(0xFF0A013A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101010)
val onBackgroundDark = Color(0xFFF6F6F6)
val surfaceDark = Color(0xFF101412)
val onSurfaceDark = Color(0xFFE0E3E0)
val surfaceVariantDark = Color(0xFF3F4944)
val onSurfaceVariantDark = Color(0xFFBEC9C3)
val outlineDark = Color(0xFF89938E)
val outlineVariantDark = Color(0xFF3F4944)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E3E0)
val inverseOnSurfaceDark = Color(0xFF2D312F)
val inversePrimaryDark = Color(0xFF196A55)
val surfaceDimDark = Color(0xFF101412)
val surfaceBrightDark = Color(0xFF363A38)
val surfaceContainerLowestDark = Color(0xFF0B0F0D)
val surfaceContainerLowDark = Color(0xFF181C1B)
val surfaceContainerDark = Color(0xFF1C201F)
val surfaceContainerHighDark = Color(0xFF272B29)
val surfaceContainerHighestDark = Color(0xFF323633)

object CoreColor {
    val warning = Color(0xFFECAF00)
    val onWarning = Color(0xFFFFFFFF)
}